// import { Geist, Geist_Mono } from "next/font/google";
'use client'
import { Dosis } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import {config} from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;
import Header from "./componentes/Header";
import { Provider } from "react-redux";
import { store } from "./redux/store";

const dosis = Dosis({
  subsets: ["latin"],
  variable: "--font-dosis"
})
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-dosis"
})
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dosis.variable}>
        <Provider store={store}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
