// import { Geist, Geist_Mono } from "next/font/google";
import { Dosis } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import {config} from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const dosis = Dosis({
  subsets: ["latin"],
  variable: "--font-dosis"
})
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-dosis"
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    /> */}
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={dosis.variable}
      >
        {children}
      </body>
    </html>
  );
}
